// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_OzbZ107mFQ4LBa_P8RkTMmp6VRZwWo0',
    appId: '1:706967235429:web:1d793f02657a3e7d540f8c',
    messagingSenderId: '706967235429',
    projectId: 'lmcapq',
    authDomain: 'lmcapq.firebaseapp.com',
    storageBucket: 'lmcapq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA777C35QI9bHD4v7giyXfjfoViRcU-vC0',
    appId: '1:706967235429:android:1b01ea1dbeb70fa7540f8c',
    messagingSenderId: '706967235429',
    projectId: 'lmcapq',
    storageBucket: 'lmcapq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-MDLoH6omfYnM0Z2JnIUL_zE0E4O9D1M',
    appId: '1:706967235429:ios:17cf531d0add042a540f8c',
    messagingSenderId: '706967235429',
    projectId: 'lmcapq',
    storageBucket: 'lmcapq.firebasestorage.app',
    iosBundleId: 'com.example.bike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-MDLoH6omfYnM0Z2JnIUL_zE0E4O9D1M',
    appId: '1:706967235429:ios:17cf531d0add042a540f8c',
    messagingSenderId: '706967235429',
    projectId: 'lmcapq',
    storageBucket: 'lmcapq.firebasestorage.app',
    iosBundleId: 'com.example.bike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_OzbZ107mFQ4LBa_P8RkTMmp6VRZwWo0',
    appId: '1:706967235429:web:db557ab72346fb72540f8c',
    messagingSenderId: '706967235429',
    projectId: 'lmcapq',
    authDomain: 'lmcapq.firebaseapp.com',
    storageBucket: 'lmcapq.firebasestorage.app',
  );
}
